const tilePairs = [
  { id: 1, name: 'a', image: 'src/assets/tiles-img/ghosteppz.png' },
  { id: 2, name: 'a', image: 'src/assets/tiles-img/ghosteppz.png' },
  { id: 3, name: 'b', image: 'src/assets/tiles-img/patollo.png'  },
  { id: 4, name: 'b', image: 'src/assets/tiles-img/patollo.png'  },
  { id: 5, name: 'c', image: 'src/assets/tiles-img/kazhuja.png'  },
  { id: 6, name: 'c', image: 'src/assets/tiles-img/kazhuja.png'  },
  { id: 7, name: 'd', image: 'src/assets/tiles-img/ananas.png'  },
  { id: 8, name: 'd', image: 'src/assets/tiles-img/ananas.png'  },
  { id: 9, name: 'e', image: 'src/assets/tiles-img/toxic.png'  },
  { id: 10, name: 'e', image: 'src/assets/tiles-img/toxic.png'  },
  { id: 11, name: 'f', image: 'src/assets/tiles-img/misiek.png'  },
  { id: 12, name: 'f', image: 'src/assets/tiles-img/misiek.png'  },
  { id: 13, name: 'g', image: 'src/assets/tiles-img/tatsumi.png'  },
  { id: 14, name: 'g', image: 'src/assets/tiles-img/tatsumi.png'  },
  { id: 15, name: 'h', image: 'src/assets/tiles-img/jabol.png'  },
  { id: 16, name: 'h', image: 'src/assets/tiles-img/jabol.png'  },
  { id: 17, name: 'i', image: 'src/assets/tiles-img/wewior.png'  },
  { id: 18, name: 'i', image: 'src/assets/tiles-img/wewior.png'  },
  { id: 19, name: 'j', image: 'src/assets/tiles-img/whicior.png'  },
  { id: 20, name: 'j', image: 'src/assets/tiles-img/whicior.png'  },
  { id: 21, name: 'k', image: 'src/assets/tiles-img/kluchams.png'  },
  { id: 22, name: 'k', image: 'src/assets/tiles-img/kluchams.png'  },
  { id: 23, name: 'l', image: 'src/assets/tiles-img/megamind.png'  },
  { id: 24, name: 'l', image: 'src/assets/tiles-img/megamind.png'  },
  { id: 25, name: 'm', image: 'src/assets/tiles-img/keeto.png'  },
  { id: 26, name: 'm', image: 'src/assets/tiles-img/keeto.png'  },
  { id: 27, name: 'n', image: 'src/assets/tiles-img/jakubenz.png'  },
  { id: 28, name: 'n', image: 'src/assets/tiles-img/jakubenz.png'  },
  { id: 29, name: 'p', image: 'src/assets/tiles-img/gigasumi.png'  },
  { id: 30, name: 'p', image: 'src/assets/tiles-img/gigasumi.png'  },

];

export default tilePairs;
