const tilePairs = [
    { id: 1, name: 'A' },
    { id: 2, name: 'A' },
    { id: 3, name: 'B' },
    { id: 4, name: 'B' },
    { id: 5, name: 'C' },
    { id: 6, name: 'C' },
    { id: 7, name: 'D' },
    { id: 8, name: 'D' },
    { id: 9, name: 'E' },
    { id: 10, name: 'E' },
    { id: 11, name: 'F' },
    { id: 12, name: 'F' },
    { id: 13, name: 'G' },
    { id: 14, name: 'G' },
    { id: 15, name: 'H' },
    { id: 16, name: 'H' },
    { id: 17, name: 'I' },
    { id: 18, name: 'I' },
    { id: 19, name: 'J' },
    { id: 20, name: 'J' },
    { id: 21, name: 'K' },
    { id: 22, name: 'K' },
    { id: 23, name: 'L' },
    { id: 24, name: 'L' },
    { id: 25, name: 'M' },
    { id: 26, name: 'M' },
    { id: 27, name: 'N' },
    { id: 28, name: 'N' },
    { id: 29, name: 'O' },
    { id: 30, name: 'O' },
  ];

export default tilePairs;