const tilePairs = [
  { id: 1, name: 'a', image: '/src/assets/ghosteppz.png' },
  { id: 2, name: 'a', image: '/src/assets/ghosteppz.png' },
  { id: 3, name: 'b', image: '/src/assets/patollo.png'  },
  { id: 4, name: 'b', image: '/src/assets/patollo.png'  },
  { id: 5, name: 'c', image: '/src/assets/kazhuja.png'  },
  { id: 6, name: 'c', image: '/src/assets/kazhuja.png'  },
  { id: 7, name: 'd', image: '/src/assets/ananas.png'  },
  { id: 8, name: 'd', image: '/src/assets/ananas.png'  },
  { id: 9, name: 'e', image: '/src/assets/toxic.png'  },
  { id: 10, name: 'e', image: '/src/assets/toxic.png'  },
  { id: 11, name: 'f', image: '/src/assets/misiek.png'  },
  { id: 12, name: 'f', image: '/src/assets/misiek.png'  },
  { id: 13, name: 'g', image: '/src/assets/tatsumi.png'  },
  { id: 14, name: 'g', image: '/src/assets/tatsumi.png'  },
  { id: 15, name: 'h', image: '/src/assets/jabol.png'  },
  { id: 16, name: 'h', image: '/src/assets/jabol.png'  },
  { id: 17, name: 'i', image: '/src/assets/wewior.png'  },
  { id: 18, name: 'i', image: '/src/assets/wewior.png'  },
  { id: 19, name: 'j', image: '/src/assets/whicior.png'  },
  { id: 20, name: 'j', image: '/src/assets/whicior.png'  },
  { id: 21, name: 'k', image: '/src/assets/kluchams.png'  },
  { id: 22, name: 'k', image: '/src/assets/kluchams.png'  },
  { id: 23, name: 'l', image: '/src/assets/megamind.png'  },
  { id: 24, name: 'l', image: '/src/assets/megamind.png'  },
  { id: 25, name: 'm', image: '/src/assets/keeto.png'  },
  { id: 26, name: 'm', image: '/src/assets/keeto.png'  },
  { id: 27, name: 'n', image: '/src/assets/jakubenz.png'  },
  { id: 28, name: 'n', image: '/src/assets/jakubenz.png'  },
  { id: 29, name: 'p', image: '/src/assets/gigasumi.png'  },
  { id: 30, name: 'p', image: '/src/assets/gigasumi.png'  },

];

export default tilePairs;
